levels:
  0: Strange
  5: Unremarkable
  10: Scarcely Lethal
  15: Mildly Menacing
  25: Somewhat Threatening
  50: Uncharitable
  75: Notably Dangerous
  100: Sufficiently Lethal
  125: Truly Feared
  150: Spectacularly Lethal
  175: Gore Spattered
  200: Wicked Nasty
  225: Positively Inhumane
  249: Totally Ordinary
  250: Face Melting
  275: Rage Inducing
  300: Server Clearing
  350: Epic
  400: Legendary
  450: Endian
  500: Notch's Own
idstrings:
  - 'Strange Weapon #{#}'
  - 'Level: {#}'
datastorage: yaml
taglengthlimit: 50
maxparts: 3
durability: true
drops:
  itemDropLimit: 9
  itemDropReset: 10080
  itemDropRollMaxTime: 70
  itemDropRollMinTime: 30
  crateDropLimit: 3
  crateDropReset: 10080
  crateDropRollMaxTime: 70
  crateDropRollMinTime: 30
database:
  url: jdbc:mysql://localhost:3306/database
  username: minecraft
  password: lolololol
crates: {}
drops: {}